name: geodesy
description: A Dart library for geodesic and trigonometric calculations working
  with points and paths
version: 0.4.0-nullsafety.0
homepage: https://github.com/wingkwong/geodesy
author: WONG, Wing Kam <wingkwong.code@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  latlong2: ^0.8.0
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.16.8
